---
roles:
  - name: geerlingguy.docker
    version: 8.0.0
    # src: https://github.com/geerlingguy/ansible-role-docker.git
  - name: geerlingguy.clamav
    version: 2.1.0
    # src: https://github.com/geerlingguy/ansible-role-clamav.git
